### ISSUE TITLE
Custom squid like hosts_file

### ISSUE THREAD

**Issue by pwFoo** [caddyserver/forwardproxy#10]
I have a special use case and would need to use a custom hosts file instead of /etc/hosts.
Would it possible to add such a config option like squid proxy have?
http://www.squid-cache.org/Doc/config/hosts_file/

**Comment by sergeyfrolov** [comment]
As far as I can tell, Golang doesn't have any tools to specify custom location of hosts file or manage hosts manually. Caddy also doesn't seem to provide such tools (@mholt please confirm). Implementing and using custom DNS manager might get complicated and bug-prone.
However, if your use-case is relatively common, we should probably consider implementing this in one way or another. Otherwise, you might be able to work around this by `chroot`ing the Caddy or some other filesystem tricks. @pwFoo would work for you?

**Comment by mholt** [comment]
> Caddy also doesn't seem to provide such tools (@mholt please confirm).

**Comment by pwFoo** [comment]
My use case is inside a docker container with generated hosts file, but I can't replace the /etc/hosts inside of a docker container. Maybe I could work around with an additional dns server container with dnsmasq and my generated hosts file.

Caddy not needs a reload after hosts changed and I would prefer to use caddy, but maybe it would be easier to build it with squid because of the hosts_file option. Squid need to be reconfigured after hosts changed (squid -k reconfigure, maybe sighub signal would work).

**Comment by sergeyfrolov** [comment]
> Maybe I could work around with an additional dns server container with dnsmasq and my generated hosts file.

That seems to be an elegant solution to your issue with added flexibility.
I will close the issue then, good luck setting things up!

**Comment by pmoroney** [comment]
Coredns (which is based off of caddy) can serve a hosts file as an authoritative DNS server. https://coredns.io/plugins/hosts/

**Comment by jim3ma** [comment]
@sergeyfrolov @mholt 
Another idea.
We can add custom resolver support before sending request to any sites.
When client request to access site X.com with CONNECT method.
resolve the X.com with custom resolver first(host file, dns server etc.), then connect to the server.
