### ISSUE TITLE
High amount of unclosed abandoned connections

### ISSUE THREAD

**Issue by bash99** [caddyserver/forwardproxy#33]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.0

### 2. What are you trying to do?
use caddy as a forward proxy chain

### 3. What is your entire Caddyfile?
```text:24096 {
    forwardproxy {
        response_timeout 30
        dial_timeout     30
        ports     80 443
        upstream  https://user:mypass@xxx.mydomain.com:443
    }
    root /root/bin/caddy/html
    gzip
    errors /root/bin/caddy/1936/error.log
    log /root/bin/caddy/1936/access.log
}
```
### 4. How did you run Caddy (give the full command and describe the execution environment)?
ulimit -n 16384 && caddy
on debian 9
load balanced by haproxy ( with statics ), than export to internal user.

### 6. What did you expect to see?
a few ESTABLISHED connection to remote host after running a few hours

### 7. What did you see instead (give full error messages and/or log)?
a lot of connection 
netstat -an | grep 64.xxx.xx.xxx | grep ESTABLISHED| wc -l
123
on haproxy statics page, current session is only 17 and max session is 67.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
sorry, no clue yet, I've try do curl every  15 secs,  but can not reproduce.

So I hope someone can explain upstream connection reuse and timeout rule for me.

**Comment by sergeyfrolov** [comment]
> load balanced by haproxy ( with statics ), than export to internal user.

I am not sure I understand your setup. But I understand that your issue is in a high amount of zombie connections.

Connections are not currently reused with upstream. It's a nontrivial feature, which we intend to delegate to `net/x/proxy`, once they accept https://go-review.googlesource.com/c/net/+/111135

Connections also currently don't timeout: after one side(two sides being client and upstream) hangs up, proxy will wait for the other side to hand up. And this is is bug: while we want to let other side to finish talking, if it doesn't come back, we should close the connection after some time. To fix that, I'll add timeout [here](https://github.com/caddyserver/forwardproxy/blob/master/forwardproxy.go#L111)
Perhaps, it also makes sense to add timeout for cases when both sides left and haven't had any activity for a looooong time.
cc: @bemasc
