### ISSUE TITLE
how to make caddy not listen to port 80?

### ISSUE THREAD

**Issue by luckypoem** [caddyserver/forwardproxy#50]
hi.
i'm using caddy's https proxy feature.
root@umh:~# cat /root/caddyfile
mydomain.com:3443 {
gzip
log access.log
forwardproxy
}
root@umh:~# lsof -i:80
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
caddy 349 root 6u IPv6 183473 0t0 TCP *:http (LISTEN)
root@umh:~#
root@umh:~# lsof -i:3443
COMMAND PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
caddy   349 root    5u  IPv6   183472      0t0  TCP *:3443 (LISTEN)
root@umh:~#

in my caddyfile,i didn't mention port 80,why caddy occupies/listen on port 80?
how to make caddy not listen to port 80?

**Comment by sergeyfrolov** [comment]
It uses port 80 to do the ACME-HTTP challenge (that's how you get TLS certificate)
I believe you can disable that challenge, and get TLS certificate another way, but I would not reccomend it for detectability reasons. Just use default port 80 and 443 and **pretend to be just a simple innocuous webserver: that's the whole point**.

This issue is not forwardproxy-specific and is about generic caddy usage, so it is better asked elsewhere, like https://caddy.community. I am sure caddy community had discussed this question before, try googling.
