### ISSUE TITLE
Possible to proxying video streams ?

### ISSUE THREAD

**Issue by ProTechEx** [caddyserver/forwardproxy#59]
Hi 

is it possible to proxy also video streams with different video mime types like:

iPhone Index | .m3u8 | application/x-mpegURL
iPhone Segment | .ts | video/MP2T
3GP Mobile | .3gp | video/3gpp
QuickTime | .mov | video/quicktime
A/V Interleave | .avi | video/x-msvideo
Windows Media | .wmv | video/x-ms-wmv

Tkanks and regrads

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for specific, development-focused discussions, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by mholt** [comment]
(Disregard my now-deleted comment, which was made by mistake on this issue instead of a different one.)

Can you be more specific about what you're asking? Is something not working as expected?

**Comment by sergeyfrolov** [comment]
To my knowledge, there are no issues with downloading videos via forwardproxy.
Please provide more details about what is not working as expected, and we will reopen the issue.
